import { json } from '@sveltejs/kit';
// @ts-expect-error - Generated by SvelteKit at runtime
import { env } from '$env/dynamic/private';
import { GoogleGenerativeAI } from '@google/generative-ai';
import type { RequestHandler } from './$types';

export const POST: RequestHandler = async ({ request }: { request: Request }) => {
	const apiKey = env.GEMINI_API_KEY;
	if (!apiKey) {
		console.error('GEMINI_API_KEY is missing. Check your .env file.');
		return json({ error: 'Gemini API key not configured. Please check your .env file and restart the dev server.' }, { status: 500 });
	}
	
	try {
		const formData = await request.formData();
		const audioFile = formData.get('audio');
		const songName = formData.get('songName') || 'Unknown Song';
		
		if (!audioFile || !(audioFile instanceof File)) {
			return json({ error: 'Audio file is required' }, { status: 400 });
		}
		
		// Initialize Gemini AI
		const genAI = new GoogleGenerativeAI(apiKey);
		const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-lite' });
		
		// Convert audio file to base64
		const arrayBuffer = await audioFile.arrayBuffer();
		const buffer = Buffer.from(arrayBuffer);
		const base64Audio = buffer.toString('base64');
		
		// Create prompt for evaluation
		const prompt = `You are a professional vocal coach evaluating a karaoke performance of "${songName}". 
Please provide:
1. A score from 0-100 based on pitch accuracy, rhythm, tone quality, and overall performance
2. Brief constructive feedback (2-3 sentences) in Traditional Chinese

Respond in JSON format:
{
  "score": <number 0-100>,
  "feedback": "<feedback text in Traditional Chinese>"
}`;
		
		// Note: Gemini API doesn't directly support audio input in this way
		// For MVP, we'll provide text-based evaluation
		// In production, you'd need to use speech-to-text first or use Gemini's audio capabilities
		const result = await model.generateContent(prompt);
		const response = await result.response;
		const text = response.text();
		
		// Try to parse JSON from response
		let evaluation;
		try {
			// Extract JSON from markdown code blocks if present
			const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/) || text.match(/\{[\s\S]*\}/);
			if (jsonMatch) {
				evaluation = JSON.parse(jsonMatch[1] || jsonMatch[0]);
			} else {
				// Fallback: create a basic evaluation
				evaluation = {
					score: 75,
					feedback: '錄音已收到，AI分析功能開發中。'
				};
			}
		} catch (parseError) {
			// Fallback evaluation
			evaluation = {
				score: 75,
				feedback: '錄音已收到，AI分析功能開發中。'
			};
		}
		
		// Ensure score is within valid range
		evaluation.score = Math.max(0, Math.min(100, evaluation.score || 75));
		
		return json({
			score: evaluation.score,
			feedback: evaluation.feedback || '錄音已收到，AI分析功能開發中。',
			evaluatedAt: new Date().toISOString()
		});
	} catch (err) {
		const error = err instanceof Error ? err : new Error('Unknown error');
		console.error('Gemini evaluation error:', error);
		return json({ 
			error: error.message || 'Failed to evaluate recording',
			score: 0,
			feedback: '評分時發生錯誤，請稍後再試。'
		}, { status: 500 });
	}
};
